#!/bin/bash

# set DIR variable to directory of the startup script
DIR="$(cd "$(dirname "$0")" && pwd)"

# make sure jack is not currently running
killall jackd
sleep 3
killall jackd
sleep 3

# start jack server
jackd -R -d coreaudio -p 32 &
sleep 3
jack_load netmanager

# open Max patch
open $DIR/Resuscitation-master.maxpat